# Generated by Django 6.0.5 on 2026-06-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ABA Bakong KHQR', 'ABA Bakong KHQR'), ('Manual ABA Transfer', 'Manual ABA Transfer')], default='ABA Bakong KHQR', max_length=30),
        ),
    ]
